"""character options + story.character_mode

Revision ID: 307f98f0b9fb
Revises: 54ccc16f0a8d
Create Date: 2026-06-24 14:37:14.483134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '307f98f0b9fb'
down_revision: Union[str, Sequence[str], None] = '54ccc16f0a8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('blurb', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=8), nullable=True),
    sa.Column('archetype', sa.String(length=24), server_default='warrior', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('stories', sa.Column('character_mode', sa.String(length=20), server_default='classes', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'character_mode')
    op.drop_table('character_options')
    # ### end Alembic commands ###
