"""story.active_edge_cap

Revision ID: 42bfdaa04fb2
Revises: eed33c705e97
Create Date: 2026-06-24 15:41:25.004771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42bfdaa04fb2'
down_revision: Union[str, Sequence[str], None] = 'eed33c705e97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('active_edge_cap', sa.Integer(), server_default='3', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'active_edge_cap')
    # ### end Alembic commands ###
