"""add story_nodes.is_ending

Revision ID: 54ccc16f0a8d
Revises: 5e6b985c2c10
Create Date: 2026-06-24 14:22:01.223008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54ccc16f0a8d'
down_revision: Union[str, Sequence[str], None] = '5e6b985c2c10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story_nodes', sa.Column('is_ending', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story_nodes', 'is_ending')
    # ### end Alembic commands ###
