"""rpg: edges, outcomes, effects, items, runs, node kinds

Revision ID: 5e6b985c2c10
Revises: b10efe75a434
Create Date: 2026-06-24 11:36:03.504028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e6b985c2c10'
down_revision: Union[str, Sequence[str], None] = 'b10efe75a434'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=True),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('kind', sa.String(length=16), server_default='consumable', nullable=False),
    sa.Column('on_use', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('from_node_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=280), nullable=True),
    sa.Column('kind', sa.String(length=10), server_default='plain', nullable=False),
    sa.Column('check_stat', sa.String(length=12), nullable=True),
    sa.Column('check_dc', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['from_node_id'], ['story_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_edges_from_node', 'edges', ['from_node_id'], unique=False)
    op.create_index('ix_edges_story', 'edges', ['story_id'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('current_node_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=12), server_default='active', nullable=False),
    sa.Column('party_gold', sa.Integer(), server_default='0', nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['current_node_id'], ['story_nodes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_runs_user_story', 'runs', ['user_id', 'story_id'], unique=False)
    op.create_table('edge_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('edge_id', sa.Integer(), nullable=False),
    sa.Column('band', sa.String(length=16), server_default='plain', nullable=False),
    sa.Column('to_node_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['edge_id'], ['edges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_node_id'], ['story_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('edge_id', 'band', name='uq_outcome_edge_band')
    )
    op.create_table('requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('edge_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=12), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['edge_id'], ['edges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('run_characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), server_default='Adventurer', nullable=False),
    sa.Column('char_class', sa.String(length=24), nullable=True),
    sa.Column('strength', sa.Integer(), server_default='10', nullable=False),
    sa.Column('dexterity', sa.Integer(), server_default='10', nullable=False),
    sa.Column('constitution', sa.Integer(), server_default='10', nullable=False),
    sa.Column('intelligence', sa.Integer(), server_default='10', nullable=False),
    sa.Column('wisdom', sa.Integer(), server_default='10', nullable=False),
    sa.Column('charisma', sa.Integer(), server_default='10', nullable=False),
    sa.Column('hp', sa.Integer(), server_default='20', nullable=False),
    sa.Column('max_hp', sa.Integer(), server_default='20', nullable=False),
    sa.Column('status', sa.String(length=8), server_default='alive', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('run_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'key', name='uq_run_flag_key')
    )
    op.create_table('run_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('edge_id', sa.Integer(), nullable=True),
    sa.Column('arrived_node_id', sa.Integer(), nullable=True),
    sa.Column('roll_d20', sa.Integer(), nullable=True),
    sa.Column('modifier', sa.Integer(), nullable=True),
    sa.Column('dc', sa.Integer(), nullable=True),
    sa.Column('band_result', sa.String(length=16), nullable=True),
    sa.Column('effects_applied', sa.JSON(), nullable=True),
    sa.Column('snapshot', sa.JSON(), nullable=True),
    sa.Column('undone', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['arrived_node_id'], ['story_nodes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['edge_id'], ['edges.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_run_steps_run_seq', 'run_steps', ['run_id', 'seq'], unique=False)
    op.create_table('effects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outcome_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=24), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('stat', sa.String(length=12), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('flag_key', sa.String(length=64), nullable=True),
    sa.Column('flag_value', sa.String(length=255), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['outcome_id'], ['edge_outcomes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('run_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['run_characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('stories', sa.Column('mode', sa.String(length=20), server_default='story', nullable=False))
    op.add_column('stories', sa.Column('death_policy', sa.String(length=20), server_default='save_anywhere', nullable=False))
    op.add_column('story_nodes', sa.Column('kind', sa.String(length=20), server_default='story', nullable=False))
    # ### end Alembic commands ###

    _backfill_plain_edges()


def _backfill_plain_edges() -> None:
    """Convert every existing node into the new edge model: one plain Edge leading
    into it (from its parent, or off the blurb when top-level) + a single plain
    EdgeOutcome. Preserves edge_prompt as the edge label. No content is lost; the
    new tables are dropped on downgrade so this data goes with them."""
    bind = op.get_bind()
    nodes = bind.execute(sa.text(
        "SELECT id, story_id, parent_node_id, user_id, edge_prompt "
        "FROM story_nodes ORDER BY id"
    )).fetchall()
    for n in nodes:
        edge_id = bind.execute(
            sa.text(
                "INSERT INTO edges (story_id, from_node_id, label, kind, created_by) "
                "VALUES (:sid, :pid, :label, 'plain', :uid) RETURNING id"
            ),
            {"sid": n.story_id, "pid": n.parent_node_id,
             "label": n.edge_prompt, "uid": n.user_id},
        ).scalar()
        bind.execute(
            sa.text(
                "INSERT INTO edge_outcomes (edge_id, band, to_node_id) "
                "VALUES (:eid, 'plain', :nid)"
            ),
            {"eid": edge_id, "nid": n.id},
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story_nodes', 'kind')
    op.drop_column('stories', 'death_policy')
    op.drop_column('stories', 'mode')
    op.drop_table('run_inventory')
    op.drop_table('effects')
    op.drop_index('ix_run_steps_run_seq', table_name='run_steps')
    op.drop_table('run_steps')
    op.drop_table('run_flags')
    op.drop_table('run_characters')
    op.drop_table('requirements')
    op.drop_table('edge_outcomes')
    op.drop_index('ix_runs_user_story', table_name='runs')
    op.drop_table('runs')
    op.drop_index('ix_edges_story', table_name='edges')
    op.drop_index('ix_edges_from_node', table_name='edges')
    op.drop_table('edges')
    op.drop_table('items')
    # ### end Alembic commands ###
