"""genres, ratings, auth fields

Revision ID: b10efe75a434
Revises: 984c13a2e858
Create Date: 2026-06-22 20:15:40.625729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b10efe75a434'
down_revision: Union[str, Sequence[str], None] = '984c13a2e858'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('genre', sa.String(length=40), server_default='general', nullable=False))
    op.add_column('stories', sa.Column('rating', sa.String(length=10), server_default='pg', nullable=False))
    op.drop_constraint(op.f('stories_publish_date_key'), 'stories', type_='unique')
    op.create_unique_constraint('uq_story_day_genre_rating', 'stories', ['publish_date', 'genre', 'rating'])
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'password_hash')
    op.drop_constraint('uq_story_day_genre_rating', 'stories', type_='unique')
    op.create_unique_constraint(op.f('stories_publish_date_key'), 'stories', ['publish_date'])
    op.drop_column('stories', 'rating')
    op.drop_column('stories', 'genre')
    # ### end Alembic commands ###
