"""edge.status (branch economy)

Revision ID: eed33c705e97
Revises: c0bbb19de8b8
Create Date: 2026-06-24 15:37:25.968499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eed33c705e97'
down_revision: Union[str, Sequence[str], None] = 'c0bbb19de8b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('edges', sa.Column('status', sa.String(length=12), server_default='active', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('edges', 'status')
    # ### end Alembic commands ###
